config/routes.rb
Rails.application.routes.draw do
  root controller: :hello_dockers, action: :index

  resources :hello_dockers do
    collection do
      post "index_add"
      delete "index_destroy"
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_dockers_controller.rb
class HelloDockersController < ApplicationController

  def index
    @messages = Message.all

    @test = ENV['APP_DATABASE_HOST']

  end

  def index_add
    Message.create(display_message: params[:display_message]).save
    redirect_to root_path
  end

  def index_destroy
    Message.find(params[:format]).destroy!
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_dockers_helper.rb
module HelloDockersHelper
end

app/views/hello_dockers/index.html.erb
<div class="container">
<table class="table table-striped table-bordered">
  <% @messages.each do |message|%>
    <tr>
      <td><label class="pull-left"><%= message.display_message %></label></td>
      <td><%= button_to '削除', index_destroy_hello_dockers_path( message.id), method: :delete, class: "btn btn-info"%></td>
    </tr>
  <% end %>

</table>


<hr>

<label><%= @test %></label>


<%= form_with(url: index_add_hello_dockers_path) do |form| %>

    <div class="row">
      <div class="col-8">
  <%= form.text_field :display_message %>
      </div>
        <div class="col-2">
  <%= form.submit "追加", class: "btn btn-info"%>
        </div>
    </div>

<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DockerTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>